<a href="https://colab.research.google.com/github/DevanshikaPiparsania/Basic-Fundamentals-Presentations/blob/main/Cleaning_Data_With_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cleaning Data with Pandas**

Often times data is incomplete or found from many dfferent sources causing there to be lots of formatting issues in the data. For this reason it is integral to be able to clean the data before beginning.

In [7]:
import pandas as pd
data = "/content/sample_data/Sportsmans - Sheet1 (1).csv"
df = pd.read_csv(data)
df.head(10)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0           1     TOM    BAL         Catcher           74   189.0  22.99
1           2     TOM    BAL         Catcher           74   189.0  22.99
2           3   Marry    BAL         Catcher           72   210.0  30.78
3           4  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4           5     Bat    BAL   First Baseman           73   188.0  35.71
5           6  Robert    BAL  Second Baseman          NaN   176.0  29.39
6           7     Mora   BAL       Shortstop          NaN   209.0  30.77
7           8  Stefin    BAL   Third Baseman          NaN   200.0  35.07
8           9   Rohan    BAL   Third Baseman          NaN   231.0  30.19
9          10  Joshif    BAL       Outfilder          NaN   180.0  27.05

INTRODUCING THE DATA

Here is the data that we will be using. There are certain portions of the data that is missing .For example the ages of the 12th - 53rd players are all missing and replaced with NaN(Not a Number) in the dataset. There are also number that are in the wrong format("Seventy Three" instead of 73) and duplicates of the same person.

In [8]:
df.head(10)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0           1     TOM    BAL         Catcher           74   189.0  22.99
1           2     TOM    BAL         Catcher           74   189.0  22.99
2           3   Marry    BAL         Catcher           72   210.0  30.78
3           4  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4           5     Bat    BAL   First Baseman           73   188.0  35.71
5           6  Robert    BAL  Second Baseman          NaN   176.0  29.39
6           7     Mora   BAL       Shortstop          NaN   209.0  30.77
7           8  Stefin    BAL   Third Baseman          NaN   200.0  35.07
8           9   Rohan    BAL   Third Baseman          NaN   231.0  30.19
9          10  Joshif    BAL       Outfilder          NaN   180.0  27.05

HOW DO YOU FIX MISSING DATA

Lets start by learning how to fix missing data. There are few approaches you can take to solving the problem of missing data depending on how large your detaset is and how accurate you want your result to be.

If your data is large enough the easiest way to trackle missing data is to just remove all rows with missing data