<a href="https://colab.research.google.com/github/DevanshikaPiparsania/Basic-Fundamentals-Presentations/blob/main/Cleaning_Data_With_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cleaning Data with Pandas**

Often times data is incomplete or found from many dfferent sources causing there to be lots of formatting issues in the data. For this reason it is integral to be able to clean the data before beginning.

In [27]:
import pandas as pd
data = "/content/sample_data/Sportsmans - Sheet1 (2).csv"
df = pd.read_csv(data)
df.head(10)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0         NaN     TOM    BAL         Catcher           74   189.0  22.99
1         NaN     TOM    BAL         Catcher           74   189.0  22.99
2         NaN   Marry    BAL         Catcher           72   210.0  30.78
3         NaN  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4         NaN     Bat    BAL   First Baseman           73   188.0  35.71
5         NaN  Robert    BAL  Second Baseman          NaN   176.0  29.39
6         NaN     Mora   BAL       Shortstop          NaN   209.0  30.77
7         NaN  Stefin    BAL   Third Baseman          NaN   200.0  35.07
8         NaN   Rohan    BAL   Third Baseman          NaN   231.0  30.19
9         NaN  Joshif    BAL       Outfilder          NaN   180.0  27.05

INTRODUCING THE DATA

Here is the data that we will be using. There are certain portions of the data that is missing .For example the ages of the 12th - 53rd players are all missing and replaced with NaN(Not a Number) in the dataset. There are also number that are in the wrong format("Seventy Three" instead of 73) and duplicates of the same person.

In [29]:
df.head(10)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0         NaN     TOM    BAL         Catcher           74   189.0  22.99
1         NaN     TOM    BAL         Catcher           74   189.0  22.99
2         NaN   Marry    BAL         Catcher           72   210.0  30.78
3         NaN  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4         NaN     Bat    BAL   First Baseman           73   188.0  35.71
5         NaN  Robert    BAL  Second Baseman          NaN   176.0  29.39
6         NaN     Mora   BAL       Shortstop          NaN   209.0  30.77
7         NaN  Stefin    BAL   Third Baseman          NaN   200.0  35.07
8         NaN   Rohan    BAL   Third Baseman          NaN   231.0  30.19
9         NaN  Joshif    BAL       Outfilder          NaN   180.0  27.05

HOW DO YOU FIX MISSING DATA

Lets start by learning how to fix missing data. There are few approaches you can take to solving the problem of missing data depending on how large your detaset is and how accurate you want your result to be.

If your data is large enough the easiest way to trackle missing data is to just remove all rows with missing data

In [30]:
new_df = df.dropna()
print("original length:",len(df),"new length:",len(new_df))
new_df.head(10)

original length: 10 new length: 0

Empty DataFrame
Columns: [Unnamed: 0, Name , Team , Position , Height, Weight, Age]
Index: []

As you can see in the head of the dataset. The new dataframe has removed all the columns that had missing values. (If you want to change the original DataFrame you can do ````df.dropna(inplace = True)````)

While removing all the missing entries can be helpful with a large dataset it can be detrimental otherwise. Machine learning finds pattern from data and without enough data it will not be able to find the correct patterns. in this case there are a few ways you can trackle this problem.

1. Replace all the NaN values with a specific number.

In [31]:
new_df = df.fillna(130) # add a second paramenter inplace == True if you want to change oriinal dataframe
new_df.head(10)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0       130.0     TOM    BAL         Catcher           74   189.0  22.99
1       130.0     TOM    BAL         Catcher           74   189.0  22.99
2       130.0   Marry    BAL         Catcher           72   210.0  30.78
3       130.0  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4       130.0     Bat    BAL   First Baseman           73   188.0  35.71
5       130.0  Robert    BAL  Second Baseman          130   176.0  29.39
6       130.0     Mora   BAL       Shortstop          130   209.0  30.77
7       130.0  Stefin    BAL   Third Baseman          130   200.0  35.07
8       130.0   Rohan    BAL   Third Baseman          130   231.0  30.19
9       130.0  Joshif    BAL       Outfilder          130   180.0  27.05

Now all the NaN values have been replaced with 130, but if you notice carefully our original dataset had NaN values in different columns. what if we want to change the NaN values specific to the column that they are in

In [32]:
new_df = df.copy()
new_df["Height"].fillna(0,inplace=True)
new_df.head(15)#look at 10-14 height

<ipython-input-32-714e51e97df4>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df["Height"].fillna(0,inplace=True)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0         NaN     TOM    BAL         Catcher           74   189.0  22.99
1         NaN     TOM    BAL         Catcher           74   189.0  22.99
2         NaN   Marry    BAL         Catcher           72   210.0  30.78
3         NaN  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4         NaN     Bat    BAL   First Baseman           73   188.0  35.71
5         NaN  Robert    BAL  Second Baseman            0   176.0  29.39
6         NaN     Mora   BAL       Shortstop            0   209.0  30.77
7         NaN  Stefin    BAL   Third Baseman            0   200.0  35.07
8         NaN   Rohan    BAL   Third Baseman            0   231.0  30.19
9         NaN  Joshif    BAL       Outfilder            0   180.0  27.05

Great now we have changed a specific columnn NaN values, Howeve, just replacing the NaN values with an arbitary number is not a good replacement as it can skew our results a lot depending on how man NaN values there are in the dataset. There has to be better way to replace the NaN values but not skew the dataset in any certain way. That bring us to our second technique of replacing. We can replace it with the mean, median or mode

In [33]:
new_df = df.copy()
new_df["Age"].fillna(df["Age"].mean(),inplace=True)
new_df.head(15) #look at 10 ages

<ipython-input-33-7f6fa0d8b538>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df["Age"].fillna(df["Age"].mean(),inplace=True)

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0         NaN     TOM    BAL         Catcher           74   189.0  22.99
1         NaN     TOM    BAL         Catcher           74   189.0  22.99
2         NaN   Marry    BAL         Catcher           72   210.0  30.78
3         NaN  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4         NaN     Bat    BAL   First Baseman           73   188.0  35.71
5         NaN  Robert    BAL  Second Baseman          NaN   176.0  29.39
6         NaN     Mora   BAL       Shortstop          NaN   209.0  30.77
7         NaN  Stefin    BAL   Third Baseman          NaN   200.0  35.07
8         NaN   Rohan    BAL   Third Baseman          NaN   231.0  30.19
9         NaN  Joshif    BAL       Outfilder          NaN   180.0  27.05

FIXING INCORRECT FORMAT

During your experimentation you may have noticed you were not able to change the label to 'Height'. Why was this? well if you look at the data on row 3 the height value is in the wrong format.  It is written as string "Seventy two".  how do we fix this?

In this case to best way to solve the issue is to brute force it, You can go through and see what values are in the wrong format and have them manually changed like so.

In [34]:
new_df = df.copy()
new_df.loc[3,'Height']= 72
new_df.head(5)
#new_df["Height"].astype('int64') once removing Na because it currently has the dtype of object due to the incorrect formatting issue abd to find the mean we need to be an int

   Unnamed: 0    Name  Team       Position  Height  Weight    Age
0         NaN     TOM    BAL        Catcher     74   189.0  22.99
1         NaN     TOM    BAL        Catcher     74   189.0  22.99
2         NaN   Marry    BAL        Catcher     72   210.0  30.78
3         NaN  Joshon    BAL  First Baseman     72   210.0  35.43
4         NaN     Bat    BAL  First Baseman     73   188.0  35.71

Sometime, there will be dates in the incorrect format. In this case you can do the code below

In [ ]:
df['Date'] = pd.to_datetime(df['Date']) #replace incorrect format with NaT(Not a Time)
df.dropna(subset=['Date'], inplace=True)

WHAT ABOUT DUPLICATES

In [35]:
new_df = df.drop_duplicates()
new_df.head()

   Unnamed: 0    Name  Team        Position        Height  Weight    Age
0         NaN     TOM    BAL         Catcher           74   189.0  22.99
2         NaN   Marry    BAL         Catcher           72   210.0  30.78
3         NaN  Joshon    BAL   First Baseman  seventy two   210.0  35.43
4         NaN     Bat    BAL   First Baseman           73   188.0  35.71
5         NaN  Robert    BAL  Second Baseman          NaN   176.0  29.39

PULL it all Together

In [38]:
# Replace Incorrect Formatting Issue
df.loc[3,'Height'] = 72
pd.to_numeric(df['Height'])
#Replace all NaN values with the mean of the column \
df["Height"].fillna(0,inplace=True)
df["Height"]= df["Height"].astype('int64')
df["Height"] = df["Height"].replace(0, df["Height"].mean()).ffill()
#Drop Duplicates
df.drop_duplicates(inplace=True)

df.head(10)

<ipython-input-38-7a7461332105>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Height"].fillna(0,inplace=True)

   Unnamed: 0    Name  Team        Position   Height  Weight    Age
0         NaN     TOM    BAL         Catcher    74.0   189.0  22.99
2         NaN   Marry    BAL         Catcher    72.0   210.0  30.78
3         NaN  Joshon    BAL   First Baseman    72.0   210.0  35.43
4         NaN     Bat    BAL   First Baseman    73.0   188.0  35.71
5         NaN  Robert    BAL  Second Baseman    36.5   176.0  29.39
6         NaN     Mora   BAL       Shortstop    36.5   209.0  30.77
7         NaN  Stefin    BAL   Third Baseman    36.5   200.0  35.07
8         NaN   Rohan    BAL   Third Baseman    36.5   231.0  30.19
9         NaN  Joshif    BAL       Outfilder    36.5   180.0  27.05